### ISSUE TITLE
README.md skills examples different from demos and PRs

### ISSUE THREAD

**Issue by jimmysjolund** [instructlab/taxonomy#1133]
**Describe the bug/problem**
When reading through the documentation it seems to me that the examples in the README.md on Skills show different yaml layout than what is used in different demo videos and actual PRs.

As example from https://github.com/instructlab/taxonomy/blob/main/README.md#getting-started-with-skill-contributions :

```
Freeform compositional skill: YAML example
version: 2
task_description: 'Teach the model how to rhyme.'
created_by: juliadenham
seed_examples:
  - question: What are 5 words that rhyme with horn?
    answer: warn, torn, born, thorn, and corn.
```
But in PRs and demo's I have watched the structure usually looks like:

```
created_by: jimmysjolund
seed_examples:
  - answer: warn, torn, born, thorn, and corn.
    question: What are 5 words that rhyme with horn?
```

**Response that you expected instead**
I expected examples and actual contributions to look the same. I would be able to update the documentation, but want to check if this actually is an issue or me misunderstanding.
