### ISSUE TITLE
ci: Check commit sha for knowledge contributions

### ISSUE THREAD

**Issue by ckadner** [instructlab/taxonomy#1188]
@bjhargrave -- We may want to add a check (linter or separate) to verify knowledge documents are actually "available" with the specified commit `sha`

So this part of the `qna.yaml` ...

```yaml
document:
  repo: https://github.com/juliadenham/Summit_knowledge
  commit: ad185efec4dad89bf611d4b9aa8641155cb25d91
  patterns:
    - BBC_studios.md
```

Would "translate" to a URL like this ...

```Python
url = f"https://raw.githubusercontent.com/{repo}/{commit}/{patterns[0]}"
```

And then we could use the Github Python API or even just Python requests to check for a `200` HTTP status, similar to this simple `curl` example:

```sh
curl -o /dev/null -w "%{http_code}" \
    -s https://raw.githubusercontent.com/juliadenham/Summit_knowledge/ad185ef/BBC_studios.md

200
```
